spring:
  application:
    name: Workshop_18_Spring_AI_Resume_Evaluator

  ai:
    retry:
      max-attempts: 1
    openai:
      api-key: ${OPENAI_API_KEY}

      chat:
        model: gpt-4o
        temperature: 0.2
        max-tokens: 1000